name: Build Kernel

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Timezone
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: "Asia/Makassar"

      - name: Setup MemKernel as a module (M-OUT) with specified name
        run: |
          curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s Y
          
      - name: Run Non-KSU Build Script
        run: |
          export KBUILD_BUILD_USER=g4hmx
          export KBUILD_BUILD_HOST=pocox3
          source build.sh
          echo "ZIPNAME=${ZIPNAME}" >> $GITHUB_ENV

      - name: Run KernelSU-Next Build Script
        run: |
          export KBUILD_BUILD_USER=g4hmx
          export KBUILD_BUILD_HOST=pocox3
          source build.sh --su
          echo "ZIPNAME_KSU=${ZIPNAME_KSU}" >> $GITHUB_ENV

      - name: Upload Non-KSU Artifact
        uses: actions/upload-artifact@main
        with:
          name: Non-KSU-Artifact
          path: ${{ env.ZIPNAME }}

      - name: Upload KernelSU-Next Artifact
        uses: actions/upload-artifact@main
        with:
          name: KSUNext-Artifact
          path: ${{ env.ZIPNAME_KSU }}
