name: Build Kernel

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Timezone
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: "Asia/Makassar"

      - name: Building Kernel
        run: |
          export KBUILD_BUILD_USER=RavensVenix
          export KBUILD_BUILD_HOST=Github
          source build.sh --sukisu
          echo "ZIPNAME=${ZIPNAME}" >> $GITHUB_ENV

      - name: Upload Kernel
        uses: actions/upload-artifact@main
        with:
          name: Kernel-Artifact
          path: ${{ env.ZIPNAME }}
