name: Build Kernel

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Timezone
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: "Asia/Makassar"

      - name: Building Kernel
        run: |
          export KBUILD_BUILD_USER=ravensvenix
          export KBUILD_BUILD_HOST=surya_kernel_x3
          source build.sh --yama --ksu-next --susfs
          echo "ZIPNAME=${ZIPNAME}" >> $GITHUB_ENV
          
      - name: Upload Elaina-Kernel Artifact
        uses: actions/upload-artifact@main
        with:
          name: Elaina-Kernel-Artifact
          path: ${{ env.ZIPNAME }}
